### ISSUE TITLE
Installer doesn't seem to work on my computer

### ISSUE THREAD

**Issue by AudranMey** [SillyBits/satisfactory-savegame-tool-ng#8]
Hello ! 

I'm trying to install your application to try to recover my save (desperately), but it doesn't want to isntall (even with admin rights). I got the following stack : 

![image](https://github.com/SillyBits/satisfactory-savegame-tool-ng/assets/12011991/e0a17d94-aeb7-4aad-bf68-76d4b9517a93)

Can you also explain a bit better how we are supposed to install the application and run it ? 😄

I'm looking foward to it !

**Comment by SillyBits** [comment]
Installer creation can only be done when compiling the repo on your system beforehand, and also requires a valid installation of NSIS, both seem missing.

Besides that, the tool is outdated currently, not working on the tool in foreseeable time, current state won't be able to read nor save recent Satisfactory saves.

**Comment by AudranMey** [comment]
Oh I see, welp, R.I.P my file I suppose 😢
Thanks for your reply !
